phraseapp:
  access_token: 3800ee770566faf7bde9a1af255a5a9d7894202d3be0e7dc63a1ca7eeb4c81c9
  project_id: 97b3b80146a4fb863ef5fa2bc9b6b6ee
  push:
    sources:
    - file: ./src/locale/messages.xlf
      params:
        file_format: xlf
        update_translations: true
  pull:
    targets:
      - file: ./src/locale/messages.he.xlf
        params:
          file_format: xlf
          convert_emoji: true
          locale_id: he
      - file: ./src/locale/messages.en.xlf
        params:
          file_format: xlf
          convert_emoji: true
          locale_id: en
